-- MySQL Script generated by MySQL Workbench
-- Wed Oct  3 15:11:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RallyeLecture
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RallyeLecture
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RallyeLecture` DEFAULT CHARACTER SET utf8 ;
USE `RallyeLecture` ;

-- ------------------------------------se-----------------
-- Table `RallyeLecture`.`quizz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`quizz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFiche` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idFiche_UNIQUE` (`idFiche` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`auteur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`editeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`editeur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`livre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `couverture` VARCHAR(45) NULL,
  `idQuizz` INT NOT NULL,
  `idAuteur` INT NOT NULL,
  `idEditeur` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Livre_Quizz_idx` (`idQuizz` ASC),
  INDEX `fk_Livre_auteur1_idx` (`idAuteur` ASC),
  INDEX `fk_Livre_editeur1_idx` (`idEditeur` ASC),
  CONSTRAINT `fk_Livre_Quizz`
    FOREIGN KEY (`idQuizz`)
    REFERENCES `RallyeLecture`.`quizz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livre_auteur1`
    FOREIGN KEY (`idAuteur`)
    REFERENCES `RallyeLecture`.`auteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livre_editeur1`
    FOREIGN KEY (`idEditeur`)
    REFERENCES `RallyeLecture`.`editeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `points` INT NOT NULL,
  `idQuizz` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Question_Quizz1_idx` (`idQuizz` ASC),
  CONSTRAINT `fk_Question_Quizz1`
    FOREIGN KEY (`idQuizz`)
    REFERENCES `RallyeLecture`.`quizz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`proposition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`proposition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proposition` VARCHAR(255) NOT NULL DEFAULT 0,
  `solution` INT NOT NULL,
  `idQuestion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Proposition_Question1_idx` (`idQuestion` ASC),
  CONSTRAINT `fk_Proposition_Question1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `RallyeLecture`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`rallye`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`rallye` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateDebut` DATE NOT NULL,
  `duree` INT NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`comporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`comporter` (
  `idLivre` INT NOT NULL,
  `idRallye` INT NOT NULL,
  INDEX `fk_comporter_rallye1_idx` (`idRallye` ASC),
  PRIMARY KEY (`idLivre`, `idRallye`),
  CONSTRAINT `fk_comporter_Livre1`
    FOREIGN KEY (`idLivre`)
    REFERENCES `RallyeLecture`.`livre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comporter_rallye1`
    FOREIGN KEY (`idRallye`)
    REFERENCES `RallyeLecture`.`rallye` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`enseignant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`enseignant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `idAuth` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`niveau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`niveau` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NiveauScolaire` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `anneeScolaire` VARCHAR(45) NULL,
  `idEnseignant` INT NOT NULL,
  `idNiveau` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_classe_Enseignant1_idx` (`idEnseignant` ASC),
  INDEX `fk_classe_niveau1_idx` (`idNiveau` ASC),
  CONSTRAINT `fk_classe_Enseignant1`
    FOREIGN KEY (`idEnseignant`)
    REFERENCES `RallyeLecture`.`enseignant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classe_niveau1`
    FOREIGN KEY (`idNiveau`)
    REFERENCES `RallyeLecture`.`niveau` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`eleve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`eleve` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `idAuth` INT NOT NULL,
  `idClasse` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eleve_classe1_idx` (`idClasse` ASC),
  CONSTRAINT `fk_eleve_classe1`
    FOREIGN KEY (`idClasse`)
    REFERENCES `RallyeLecture`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`participer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`participer` (
  `idRallye` INT NOT NULL,
  `idEleve` INT NOT NULL,
  PRIMARY KEY (`idRallye`, `idEleve`),
  INDEX `fk_Participer_eleve1_idx` (`idEleve` ASC),
  CONSTRAINT `fk_Participer_rallye1`
    FOREIGN KEY (`idRallye`)
    REFERENCES `RallyeLecture`.`rallye` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participer_eleve1`
    FOREIGN KEY (`idEleve`)
    REFERENCES `RallyeLecture`.`eleve` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RallyeLecture`.`reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RallyeLecture`.`reponse` (
  `idQuestion` INT NOT NULL,
  `idProposition` INT NOT NULL,
  `idParticiperRallye` INT NOT NULL,
  `idParticiperEleve` INT NOT NULL,
  PRIMARY KEY (`idQuestion`, `idProposition`, `idParticiperRallye`, `idParticiperEleve`),
  INDEX `fk_reponse_Question1_idx` (`idQuestion` ASC),
  INDEX `fk_reponse_Participer1_idx` (`idParticiperRallye` ASC, `idParticiperEleve` ASC),
  CONSTRAINT `fk_reponse_Proposition1`
    FOREIGN KEY (`idProposition`)
    REFERENCES `RallyeLecture`.`proposition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponse_Question1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `RallyeLecture`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponse_Participer1`
    FOREIGN KEY (`idParticiperRallye` , `idParticiperEleve`)
    REFERENCES `RallyeLecture`.`participer` (`idRallye` , `idEleve`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
